apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: idt5vc6er-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: idt5vc6er-go 
  name: idt5vc6er-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: idt5vc6er-go 
